# Generated by Django 4.2.7 on 2023-11-26 19:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stuff', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='books',
            name='tags',
        ),
        migrations.DeleteModel(
            name='Tag',
        ),
    ]
