# Generated by Django 4.2.7 on 2023-11-26 19:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stuff', '0002_remove_books_tags_delete_tag'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='books',
            options={'verbose_name_plural': 'Books'},
        ),
    ]
