# Generated by Django 5.0.1 on 2024-01-08 21:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stuff', '0003_alter_books_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='books',
            name='price',
            field=models.DecimalField(decimal_places=2, default=None, max_digits=5),
        ),
    ]
