# Generated by Django 5.0.1 on 2024-01-23 09:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stuff', '0005_tag_books_vote_ratio_books_vote_total_books_tags_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='books',
            name='author',
            field=models.CharField(default=None, max_length=100),
        ),
    ]
