# Generated by Django 4.2.9 on 2024-01-25 23:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stuff', '0007_order_shippingaddress_orderitem'),
    ]

    operations = [
        migrations.AddField(
            model_name='books',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
