# Generated by Django 4.2.9 on 2024-01-26 00:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stuff', '0008_books_image'),
    ]

    operations = [
        migrations.RenameField(
            model_name='orderitem',
            old_name='product',
            new_name='book',
        ),
    ]
