# Generated by Django 4.2.9 on 2024-01-27 16:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stuff', '0009_rename_product_orderitem_book'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='books',
            options={'ordering': ['id'], 'verbose_name_plural': 'Books'},
        ),
        migrations.RemoveField(
            model_name='books',
            name='vote_ratio',
        ),
        migrations.RemoveField(
            model_name='books',
            name='vote_total',
        ),
        migrations.DeleteModel(
            name='Review',
        ),
    ]
