# Generated by Django 4.2.9 on 2024-01-27 17:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stuff', '0010_alter_books_options_remove_books_vote_ratio_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='books',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='static/images/'),
        ),
    ]
