# Generated by Django 4.2.9 on 2024-01-27 17:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stuff', '0012_alter_books_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='books',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='images/'),
        ),
    ]
