# Generated by Django 4.2.9 on 2024-01-28 13:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stuff', '0013_alter_books_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='books',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='books',
            name='title',
            field=models.CharField(max_length=255),
        ),
    ]
